title: Learning Ember
description: A series of blogs written about the Ember.js framework

url: http://seawatts.github.io
baseurl: "learning-ember"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: http://seawatts.github.io
 - title: Contact
   url: http://seawatts.github.io/#contact

social:
   github: seawatts
   twitter: seawatts
   email: chris.watts.t@gmail.com

google_analytics: "UA-63487336-1"
